version: '3.7'

services:

  fast-kart:
    image: yashraj10/mmv2-fast-kart-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9092:9092"
    networks:
      - shopping-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
     

  bank:
    image: yashraj10/mmv2-bank-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9091:9091"
    networks:
      - shopping-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  api-gateway:
    image: yashraj10/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - shopping-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  eureka-server:
    image: yashraj10/mmv2-eureka-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - shopping-network

#docker run -p 9411:9411 openzipkin/zipkin:2.23

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - shopping-network
    restart: always #Restart if there is a problem starting up

networks:
  shopping-network: